-- CREATE DATABASE gymcrm;
-- DROP DATABASE gymcrm;
-- DROP TABLE IF EXISTS trainee_trainer;
-- DROP TABLE IF EXISTS training;
-- DROP TABLE IF EXISTS trainee;
-- DROP TABLE IF EXISTS trainer;
-- DROP TABLE IF EXISTS gym_user;
-- DROP TABLE IF EXISTS trainingtype;

CREATE TABLE TrainingType (
   trainingtype_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
   trainingType VARCHAR(255),
   CONSTRAINT pk_trainingtype PRIMARY KEY (trainingtype_id)
);

CREATE TABLE gym_user (
   gym_user_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
   firstName VARCHAR(255),
   lastName VARCHAR(255),
   userName VARCHAR(255),
   user_password VARCHAR(255),
   isActive BOOLEAN,
   CONSTRAINT pk_gym_user PRIMARY KEY (gym_user_id)
);

CREATE TABLE Trainer (
   trainer_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
   specialization_id BIGINT,
   gym_user_id BIGINT,
   CONSTRAINT pk_trainer PRIMARY KEY (trainer_id)
);

ALTER TABLE Trainer ADD CONSTRAINT FK_TRAINER_ON_SPECIALIZATION FOREIGN KEY (specialization_id) REFERENCES TrainingType (trainingtype_id);

ALTER TABLE Trainer ADD CONSTRAINT FK_TRAINER_ON_USER FOREIGN KEY (gym_user_id) REFERENCES gym_user (gym_user_id);

CREATE TABLE Trainee (
   trainee_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
   dateOfBirth date,
   address VARCHAR(255),
   gym_user_id BIGINT,
   CONSTRAINT pk_trainee PRIMARY KEY (trainee_id)
);

CREATE TABLE trainee_trainer (
   trainee_id BIGINT NOT NULL,
   trainer_id BIGINT NOT NULL
);

ALTER TABLE Trainee ADD CONSTRAINT FK_TRAINEE_ON_USER FOREIGN KEY (gym_user_id) REFERENCES gym_user (gym_user_id);

ALTER TABLE trainee_trainer ADD CONSTRAINT fk_tratra_on_trainee FOREIGN KEY (trainee_id) REFERENCES Trainee (trainee_id);

ALTER TABLE trainee_trainer ADD CONSTRAINT fk_tratra_on_trainer FOREIGN KEY (trainer_id) REFERENCES Trainer (trainer_id);

CREATE TABLE Training (
   training_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
   trainee_id BIGINT,
   trainer_id BIGINT,
   trainingName VARCHAR(255),
   trainingType_id BIGINT,
   trainingDay date,
   trainingDuration INTEGER,
   CONSTRAINT pk_training PRIMARY KEY (training_id)
);

ALTER TABLE Training ADD CONSTRAINT FK_TRAINING_ON_TRAINEE FOREIGN KEY (trainee_id) REFERENCES Trainee (trainee_id);

ALTER TABLE Training ADD CONSTRAINT FK_TRAINING_ON_TRAINER FOREIGN KEY (trainer_id) REFERENCES Trainer (trainer_id);

ALTER TABLE Training ADD CONSTRAINT FK_TRAINING_ON_TRAININGTYPE FOREIGN KEY (trainingType_id) REFERENCES TrainingType (trainingtype_id);